### PR TITLE
fix: Dragon movement when following the user.

### LINKED ISSUE #74: [BUG] Dragons waste huge amounts of time to travel to you when whistled at if at a different Y level.
**Describe the bug**
If a dragon is above you or below you and you whistle at them, if they're not far enough to be teleported, they will take insane amounts of time to travel to you. They will circle dozens of times instead of simply flying straight up/down.

**To Reproduce**
1. Have a dragon.
2. Fly up about 50 blocks into the air.
3. Whistle at it.
4. The dragon will start circling and will take a very long time to arrive to you.

**Expected behavior**
Dragons should fly straight to you instead of circling.

**Screenshots**
https://youtu.be/clMTGqoZQIs

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by vxern**
Fixes #74.

https://github.com/user-attachments/assets/d43c7bff-b036-476b-8dbc-c5cbad8caee1

### CODE REVIEW

File: src/main/java/dmr/DragonMounts/server/ai/navigation/DragonPathNavigation.java [hunk 1]
```diff
@@ -45,61 +52,64 @@ protected double getGroundY(Vec3 p_217794_) {
...
+            return createPathWithFlyingAllowed(pos, accuracy);
         }
 
-        resetMaxVisitedNodesMultiplier();
-
-        return path;
-    }
-
-    @Override
-    public Path createPath(Entity entity, int accuracy) {
```
Comment (vxern) [inline src/main/java/dmr/DragonMounts/server/ai/navigation/DragonPathNavigation.java:78]: `createPath(Entity entity, int accuracy)` is implemented as follows:
```java
/**
 * Returns a path to the given entity or null
 */
@Override
public Path createPath(Entity entity, int accuracy) {
    return this.createPath(entity.blockPosition(), accuracy);
}
```

Which makes this override unnecessary here.

File: src/main/java/dmr/DragonMounts/server/ai/navigation/DragonPathNavigation.java [hunk 2]
```diff
@@ -45,61 +52,64 @@ protected double getGroundY(Vec3 p_217794_) {
     }
 
     @Override
-    public @Nullable Path createPath(BlockPos pos, int accuracy) {
-        dragonNodeEvaluator.allowSwimming = false;
-        dragonNodeEvaluator.allowFlying = false;
+    public void tick() {
+        super.tick();
 
-        setMaxVisitedNodesMultiplier(5f);
```
Comment (vxern) [inline src/main/java/dmr/DragonMounts/server/ai/navigation/DragonPathNavigation.java:52]: We don't need to be setting and resetting the multiplier on every run, right?

**Review by Horeak — APPROVED** [review]
Can you do
